import { useState, useEffect, useRef } from 'react'
import { createHighlighter } from 'shiki'
import Markdown from 'react-markdown'
import PixelIcon from '../PixelIcon'
import { AgentDot } from './AgentDot'

const MOCK_MARKDOWN = `# Weekly Competitor Pricing Analysis

## Executive Summary

Pricing data was collected from **5 competitors** across 47 product SKUs. Key findings:

- **CompetitorA** dropped prices by an average of **12%** across their enterprise tier
- **CompetitorB** introduced a new usage-based pricing model, replacing flat-rate plans
- **CompetitorC** remains the most expensive option, but bundles more features at each tier
- Our pricing is **competitive at the mid-tier** but undercuts on starter plans by ~18%

## Data Collection

| Competitor | Products Scraped | Avg Price (USD) | Price Change |
|------------|-----------------|-----------------|--------------|
| CompetitorA | 12 | $49.00 | -12.3% |
| CompetitorB | 8 | $35.00 | N/A (new model) |
| CompetitorC | 15 | $89.00 | +2.1% |
| CompetitorD | 7 | $42.00 | -5.8% |
| CompetitorE | 5 | $55.00 | 0% |

## Methodology

All prices were scraped using headless browser automation with rate limiting (max 2 req/s). Currency conversion applied using live ECB rates at time of collection. Products were matched across competitors using SKU normalization and fuzzy title matching (>85% similarity threshold).

### Rate Limiting Incidents

During collection, we hit rate limits on CompetitorA after 32/47 pages. Backed off for 30 seconds and resumed successfully. No data was lost.

## Recommendations

1. **Hold current pricing** on starter tier — our 18% undercut is a strong acquisition advantage
2. **Monitor CompetitorB** closely — their usage-based model could disrupt mid-market expectations
3. **Consider bundling** at enterprise tier to compete with CompetitorC's feature-rich plans
4. Schedule follow-up analysis in **2 weeks** to track CompetitorA's pricing trajectory

---

*Generated by Scout & Forge — March 23, 2026*
`

const MOCK_CODE = `import { useState, useEffect } from 'react'

interface PaymentConfig {
  provider: 'stripe' | 'paypal'
  currency: string
  webhookSecret: string
}

export class PaymentService {
  private config: PaymentConfig
  private retryCount = 3

  constructor(config: PaymentConfig) {
    this.config = config
  }

  async processPayment(amount: number, customerId: string) {
    const session = await this.createSession({
      amount,
      currency: this.config.currency,
      customer: customerId,
      metadata: {
        timestamp: Date.now(),
        provider: this.config.provider,
      },
    })

    // Verify webhook signature before processing
    if (!this.verifySignature(session.signature)) {
      throw new PaymentError('Invalid webhook signature', {
        sessionId: session.id,
        provider: this.config.provider,
      })
    }

    for (let attempt = 0; attempt < this.retryCount; attempt++) {
      try {
        const result = await this.executeCharge(session)
        await this.notifyWebhook(result)
        return { success: true, transactionId: result.id }
      } catch (err) {
        if (attempt === this.retryCount - 1) throw err
        await this.delay(Math.pow(2, attempt) * 1000)
      }
    }
  }

  private async createSession(params: Record<string, unknown>) {
    const response = await fetch('/api/payments/session', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(params),
    })
    if (!response.ok) throw new Error('Session creation failed')
    return response.json()
  }

  private verifySignature(signature: string): boolean {
    const expected = crypto
      .createHmac('sha256', this.config.webhookSecret)
      .update(signature)
      .digest('hex')
    return crypto.timingSafeEqual(
      Buffer.from(signature),
      Buffer.from(expected)
    )
  }

  private async executeCharge(session: any) {
    return fetch('/api/payments/charge', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ sessionId: session.id }),
    }).then(r => r.json())
  }

  private async notifyWebhook(result: any) {
    await fetch(this.config.webhookUrl, {
      method: 'POST',
      body: JSON.stringify(result),
    })
  }

  private delay(ms: number) {
    return new Promise(resolve => setTimeout(resolve, ms))
  }
}`

const MOCK_COMMENTS = [
  { agent: 'Cipher', time: '5 min ago', text: 'Added retry logic with exponential backoff. Should handle transient failures from the payment provider.' },
  { agent: 'Beacon', time: '3 min ago', text: 'Looks solid. Might want to cap the retry delay — 3 attempts with exponential could be fine but worth noting.' },
]

let highlighterPromise = null
function getHighlighter() {
  if (!highlighterPromise) {
    highlighterPromise = createHighlighter({
      themes: ['github-light'],
      langs: ['typescript'],
    })
  }
  return highlighterPromise
}

function CodeViewer({ code, lang = 'typescript' }) {
  const [html, setHtml] = useState('')

  useEffect(() => {
    getHighlighter().then(highlighter => {
      const result = highlighter.codeToHtml(code, {
        lang,
        theme: 'github-light',
      })
      setHtml(result)
    })
  }, [code, lang])

  if (!html) {
    return (
      <div className="flex items-center justify-center h-full text-[var(--color-muted)]">
        <PixelIcon name="loader" size={20} className="animate-spin" />
      </div>
    )
  }

  const lineCount = code.split('\n').length

  return (
    <div className="overflow-auto h-full flex" style={{ tabSize: 2 }}>
      {/* Line numbers */}
      <div className="flex-shrink-0 py-6 pl-4 pr-2 text-right select-none">
        {Array.from({ length: lineCount }, (_, i) => (
          <div key={i} className="text-[13px] leading-relaxed font-mono text-[var(--color-muted)]/40">{i + 1}</div>
        ))}
      </div>
      {/* Code */}
      <div
        className="flex-1 text-[13px] leading-relaxed [&_pre]:py-6 [&_pre]:pr-6 [&_pre]:pl-2 [&_pre]:m-0 [&_code]:font-mono"
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  )
}

function MarkdownViewer({ content }) {
  return (
    <div className="overflow-auto h-full py-8 px-8 mx-auto max-w-[680px]
      [&_h1]:text-[17px] [&_h1]:font-bold [&_h1]:mb-4 [&_h1]:mt-0 [&_h1]:text-[var(--color-heading)]
      [&_h2]:text-[16px] [&_h2]:font-bold [&_h2]:mb-3 [&_h2]:mt-8 [&_h2]:text-[var(--color-heading)]
      [&_h3]:text-[14px] [&_h3]:font-semibold [&_h3]:mb-2 [&_h3]:mt-6 [&_h3]:text-[var(--color-heading)]
      [&_p]:text-[13px] [&_p]:leading-relaxed [&_p]:text-[var(--color-body)] [&_p]:mb-4
      [&_ul]:text-[13px] [&_ul]:leading-relaxed [&_ul]:text-[var(--color-body)] [&_ul]:mb-4 [&_ul]:pl-5 [&_ul]:list-disc
      [&_ol]:text-[13px] [&_ol]:leading-relaxed [&_ol]:text-[var(--color-body)] [&_ol]:mb-4 [&_ol]:pl-5 [&_ol]:list-decimal
      [&_li]:mb-1.5
      [&_strong]:text-[var(--color-heading)] [&_strong]:font-semibold
      [&_em]:italic
      [&_hr]:border-[var(--color-border)] [&_hr]:my-6
      [&_table]:w-full [&_table]:text-[12px] [&_table]:mb-4
      [&_th]:text-left [&_th]:text-[var(--color-heading)] [&_th]:font-semibold [&_th]:py-2 [&_th]:px-3 [&_th]:border-b [&_th]:border-[var(--color-border)] [&_th]:bg-[var(--color-bg-alt)]
      [&_td]:py-2 [&_td]:px-3 [&_td]:border-b [&_td]:border-[var(--color-border)] [&_td]:text-[var(--color-body)]
      [&_code]:font-mono [&_code]:text-[12px] [&_code]:bg-[var(--color-bg-alt)] [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded
    " style={{ fontFamily: 'var(--font-body, Sora, sans-serif)' }}>
      <Markdown>{content}</Markdown>
    </div>
  )
}

export function ReviewSheet({ open, onClose, file, type = 'code' }) {
  const [phase, setPhase] = useState(0) // 0=closed, 1=open
  const [commentText, setCommentText] = useState('')
  const [comments, setComments] = useState(MOCK_COMMENTS)
  const [vote, setVote] = useState(null) // 'up' | 'down' | null
  const overlayRef = useRef(null)

  useEffect(() => {
    if (open) {
      requestAnimationFrame(() => requestAnimationFrame(() => setPhase(1)))
      document.body.style.overflow = 'hidden'
    } else {
      setPhase(0)
    }
    return () => { document.body.style.overflow = '' }
  }, [open])

  const handleClose = () => {
    setPhase(0)
    setTimeout(onClose, 350)
  }

  useEffect(() => {
    if (!open) return
    const handler = (e) => { if (e.key === 'Escape') handleClose() }
    document.addEventListener('keydown', handler)
    return () => document.removeEventListener('keydown', handler)
  }, [open])

  const handleComment = () => {
    if (!commentText.trim()) return
    setComments(prev => [...prev, { agent: 'You', time: 'Just now', text: commentText.trim() }])
    setCommentText('')
  }

  if (!open && phase === 0) return null

  const filePath = file?.name || (type === 'markdown' ? 'reports/weekly-analysis.md' : 'src/services/payment.ts')
  const objective = file?.objective || (type === 'markdown' ? 'Weekly competitor pricing analysis' : 'Payment service security review')

  return (
    <div
      ref={overlayRef}
      className="fixed inset-0 z-[9998]"
      onClick={handleClose}
    >
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/50"
        style={{
          opacity: phase === 1 ? 1 : 0,
          backdropFilter: phase === 1 ? 'blur(8px)' : 'blur(0px)',
          WebkitBackdropFilter: phase === 1 ? 'blur(8px)' : 'blur(0px)',
          transition: 'opacity 0.3s ease-out, backdrop-filter 0.3s ease-out',
        }}
      />

      {/* Sheet */}
      <div
        className="absolute bottom-0 left-0 right-0 bg-[var(--color-surface)] rounded-t-2xl flex flex-col"
        onClick={e => e.stopPropagation()}
        style={{
          height: '95vh',
          transform: phase === 1 ? 'translateY(0)' : 'translateY(100%)',
          transition: phase === 1
            ? 'transform 0.4s cubic-bezier(0.16, 1, 0.3, 1)'
            : 'transform 0.3s cubic-bezier(0.4, 0, 1, 1)',
          boxShadow: '0 -10px 40px rgba(0,0,0,0.15)',
        }}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-3 border-b border-[var(--color-border)]">
          <div className="flex items-center gap-3 min-w-0">
            <div className="text-[13px] font-bold text-[var(--color-heading)] truncate" style={{ fontFamily: 'var(--font-display)' }}>{objective}</div>
            <span className="text-[var(--color-muted)]">/</span>
            <div className="text-[12px] font-mono text-[var(--color-muted)] truncate flex-shrink-0">{filePath}</div>
          </div>
          <div className="flex items-center gap-2 flex-shrink-0">
            {/* Thumbs up/down */}
            <button
              type="button"
              onClick={() => setVote(vote === 'up' ? null : 'up')}
              className={`w-8 h-8 flex items-center justify-center rounded-lg cursor-pointer transition-colors ${vote === 'up' ? 'bg-[var(--color-accent)]/15 text-[var(--color-accent)]' : 'text-[var(--color-muted)] hover:text-[var(--color-heading)] hover:bg-[var(--color-bg-alt)]'}`}
            >
              <PixelIcon name="thumbs-up" size={16} aria-hidden="true" />
            </button>
            <button
              type="button"
              onClick={() => setVote(vote === 'down' ? null : 'down')}
              className={`w-8 h-8 flex items-center justify-center rounded-lg cursor-pointer transition-colors ${vote === 'down' ? 'bg-red-500/15 text-red-500' : 'text-[var(--color-muted)] hover:text-[var(--color-heading)] hover:bg-[var(--color-bg-alt)]'}`}
            >
              <PixelIcon name="thumbs-down" size={16} aria-hidden="true" />
            </button>
            <div className="w-px h-5 bg-[var(--color-border)] mx-1" />
            <button
              type="button"
              onClick={handleClose}
              className="w-8 h-8 flex items-center justify-center rounded-lg text-[var(--color-muted)] hover:text-[var(--color-heading)] hover:bg-[var(--color-bg-alt)] cursor-pointer transition-colors"
            >
              <PixelIcon name="close" size={16} aria-hidden="true" />
            </button>
          </div>
        </div>

        {/* Body — code + sidebar */}
        <div className="flex flex-1 overflow-hidden">
          {/* Content area — 80% */}
          <div className="flex-[4] overflow-auto border-r border-[var(--color-border)] bg-[var(--color-bg)]">
            {type === 'markdown' ? (
              <MarkdownViewer content={MOCK_MARKDOWN} />
            ) : (
              <CodeViewer code={MOCK_CODE} />
            )}
          </div>

          {/* Sidebar — 20% */}
          <div className="flex-[1] flex flex-col min-w-[280px] max-w-[360px]">
            {/* Task details */}
            <div className="px-4 py-4 border-b border-[var(--color-border)]">
              <div className="text-[10px] font-mono uppercase tracking-wider text-[var(--color-muted)] mb-2">Task Details</div>
              <div className="space-y-1.5 text-[11px]">
                <div className="flex justify-between">
                  <span className="text-[var(--color-muted)]">Task</span>
                  <span className="text-[var(--color-heading)] font-medium font-mono">TSK-038</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-[var(--color-muted)]">Agent</span>
                  <span className="text-[var(--color-heading)] font-medium flex items-center gap-1.5">
                    <AgentDot name="Cipher" size={16} />
                    Cipher
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-[var(--color-muted)]">Status</span>
                  <span className="text-[var(--color-heading)] font-medium">Needs Review</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-[var(--color-muted)]">Files Changed</span>
                  <span className="text-[var(--color-heading)] font-medium tabular-nums">3</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-[var(--color-muted)]">Additions</span>
                  <span className="text-[var(--color-accent)] font-medium tabular-nums">+47</span>
                </div>
              </div>
            </div>

            {/* Comments */}
            <div className="flex-1 flex flex-col overflow-hidden">
              <div className="px-4 py-3">
                <div className="text-[10px] font-mono uppercase tracking-wider text-[var(--color-muted)]">Comments ({comments.length})</div>
              </div>
              <div className="flex-1 overflow-auto px-4 space-y-4">
                {comments.map((comment, i) => (
                  <div key={i} className="flex gap-2.5">
                    <AgentDot name={comment.agent} size={24} className="flex-shrink-0 mt-0.5" />
                    <div>
                      <div className="flex items-center gap-2 mb-0.5">
                        <span className="text-[12px] font-semibold text-[var(--color-heading)]">{comment.agent}</span>
                        <span className="text-[10px] text-[var(--color-muted)]">{comment.time}</span>
                      </div>
                      <p className="text-[12px] text-[var(--color-body)] leading-relaxed">{comment.text}</p>
                    </div>
                  </div>
                ))}
              </div>

              {/* Comment input */}
              <div className="px-4 py-3 border-t border-[var(--color-border)]">
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={commentText}
                    onChange={e => setCommentText(e.target.value)}
                    onKeyDown={e => { if (e.key === 'Enter') handleComment() }}
                    placeholder="Add a comment..."
                    className="flex-1 h-8 px-3 rounded-lg bg-[var(--color-bg-alt)] text-[12px] text-[var(--color-heading)] placeholder:text-[var(--color-muted)] border-none outline-none focus:ring-1 focus:ring-[var(--color-accent)]"
                  />
                  <button
                    type="button"
                    onClick={handleComment}
                    disabled={!commentText.trim()}
                    className="h-8 px-3 rounded-lg bg-[var(--color-accent)] text-[#0d2000] text-[12px] font-semibold cursor-pointer transition-[opacity,scale] duration-150 active:scale-[0.96] disabled:opacity-40 disabled:cursor-default"
                  >
                    Send
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
